# Generated by Django 3.0.4 on 2020-04-01 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('knowledge_quiz', 'Knowledge Quiz'), ('psychology_quiz', 'Psychology Quiz'), ('preferential_quiz', 'Preferential Quiz'), ('universal_quiz', 'Universal Quiz')], max_length=17)),
                ('category', models.CharField(choices=[('general_knowledge', 'General knowledge'), ('celebrities', 'Celebrities'), ('for_kids', 'For kids'), ('movies', 'Movies'), ('geography', 'Geography'), ('history', 'History'), ('literature', 'Literature'), ('people', 'People'), ('music', 'Music'), ('science', 'Science'), ('policy', 'Policy'), ('nature', 'Nature'), ('psychology', 'Psychology'), ('religion', 'Religion'), ('entertainment', 'Entertainment'), ('sport', 'Sport'), ('technology', 'Technology'), ('television', 'Television'), ('funny', 'Funny'), ('puzzles', 'Puzzles'), ('health_and_beauty', 'Health and beauty'), ('animals', 'Animals')], max_length=17)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(default='https://cdn.pixabay.com/photo/2017/01/24/00/21/question-2004314_960_720.jpg')),
                ('solves', models.PositiveIntegerField(default=0, editable=False)),
                ('is_published', models.CharField(choices=[('True', 'Publish'), ('False', 'Private')], default='True', max_length=7)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_opinions', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_opinions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='quizes.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizes.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizes.Question')),
            ],
        ),
    ]
