# Generated by Django 3.0.4 on 2020-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizopinion',
            name='content',
            field=models.TextField(max_length=1500),
        ),
    ]
