# Generated by Django 3.0.4 on 2020-04-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_auto_20200403_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizopinion',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.QuizOpinion'),
        ),
    ]
