# Generated by Django 3.0.4 on 2020-04-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_quizopinion_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizopinion',
            name='replies',
        ),
        migrations.AddField(
            model_name='quizopinion',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quizes.QuizOpinion'),
        ),
    ]
