# Generated by Django 3.0.4 on 2020-04-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_auto_20200404_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizopinion',
            options={'ordering': ['-pub_date']},
        ),
    ]
