# Generated by Django 3.0.4 on 2020-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_auto_20200407_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-solves', '-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='quizopinion',
            options={},
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_fb_and_web',
            field=models.BooleanField(default=True),
        ),
    ]
