# Generated by Django 3.0.4 on 2020-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_auto_20200408_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_url',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2017/01/24/00/21/question-2004314_960_720.jpg', null=True),
        ),
    ]
