# Generated by Django 3.0.4 on 2020-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_auto_20200411_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
