# Generated by Django 3.0.4 on 2020-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0011_quiz_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_points',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=5),
        ),
    ]
