# Generated by Django 3.0.4 on 2020-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_quiz_show_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='show_points',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='True', max_length=5),
        ),
    ]
