# Generated by Django 3.0.4 on 2020-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0014_auto_20200411_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_opinions',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='True', max_length=5),
        ),
    ]
