# Generated by Django 3.0.5 on 2020-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0015_quiz_is_opinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
