# Generated by Django 3.0.4 on 2020-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200324_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/profiles/default.jpg', upload_to='image/profiles'),
        ),
    ]
