# Generated by Django 3.0.4 on 2020-04-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200402_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(default='https://s3.eu-west-2.amazonaws.com/racingleaguehub/img/avatars/default.jpg'),
        ),
    ]
