# Generated by Django 3.0.4 on 2020-04-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200402_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_url',
        ),
    ]
