# Generated by Django 3.0.4 on 2020-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200402_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_fb_and_web',
            field=models.BooleanField(default=True),
        ),
    ]
