# Generated by Django 3.0.4 on 2020-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_show_fb_and_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, default='https://s3.eu-west-2.amazonaws.com/racingleaguehub/img/avatars/default.jpg', null=True),
        ),
    ]
