# Generated by Django 3.0.5 on 2020-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200410_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='xd'),
            preserve_default=False,
        ),
    ]
