# Generated by Django 3.0.5 on 2020-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200416_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
